### PR TITLE
VideoJS 5.0 Updates

### PR DESCRIPTION
**Pull request by forbesjo**
This PR is to update the plugin for video.js 5.0

### CODE REVIEW

**Comment by chemoish** [comment]
+1

**Comment by chemoish** [comment]
Beyond fixing the jshint, expect(8), and the two tests. What is left outstanding?

Only some of the tests pass, but works for me without any errors in Chrome `45.0.2454` on OS X `10.10.5`.

**Comment by forbesjo** [comment]
We'll see if we can make a release this week since the MSE HLS work in videojs-contrib-hls is winding down.

**Comment by richardbushell** [comment]
Hi Joe, any update on the possible release please.

**Comment by forbesjo** [comment]
2.0.0 is now available.

**Comment by forbesjo** [comment]
@tjenkinson could you open requirejs compatibility in another issue?

**Comment by chemoish** [comment]
:tada:

**Comment by richardbushell** [comment]
Hi Joe

Sorry, just seen you've closed the original issue, so I've re-posted this as a new issue.

Thanks very much for v2.0.0.

We have just tested it with DASH as first src, then MP4 as 2nd src (fallback).

Works fine in Win 8.1, on IE (Dash), Chrome (Dash), Firefox (MP4 fallback).

But on Win 7, IE fails (should fallback to MP4). It should fallback to MP4 (2nd src), but it fails with the error:
--- The Media Could Not Be Loaded... ---
Chrome (Dash) and Firefox (MP4 fallback) are fine, just fails on IE?

Any ideas on a fix?

Richard

**Comment by richardbushell** [comment]
Well done Joe, v2.0.0 working fine across the all browsers we've tested.

**Comment by sprice** [comment]
Great work! I'm assuming this can be merged?

**Comment by AlexRevin** [comment]
Does not work with requirejs yet though

**Comment by forbesjo** [comment]
Merging this in as there hasn't been any activity with version 1.x.

**Pull request merged**
