### PR TITLE
Added representation selection API

### LINKED ISSUE #161: Create player.dash.representations() API
Now that dash.js has min/max bitrate APIs it should be easy to create an API for manual quality selection. This can also be hooked into the videojs-contrib-quality-levels plugin (a general API to manipulate quality levels across playback plugins)

### PR DESCRIPTION
**Pull request by forbesjo**
Closes #161  

Todo:
- [x] Tests
- [x] Update dash.js version when available
- [x] Redo the listeners in `setupQualityLevels()`

### CODE REVIEW

**Comment by mjneil** [comment]
What is the " Redo the listeners in setupQualityLevels()" task?

**Comment by forbesjo** [comment]
That's for removing the `loadstart` listener and instead disposing qualityLevels on source handler dispose.

**Comment by mjneil** [comment]
reviewed lgtm, still needs testing

**Comment by partyconfetti** [comment]
Any update on this?

**Comment by forbesjo** [comment]
I won't be able to update this, if anyone would like to use this PR as a foundation for their own version of this feature feel free to take the code

**Pull request closed without merging**
