### PR TITLE
Expose ways to add dash plugins and to configure dash playback.

### PR DESCRIPTION
**Pull request by nweber**
Added information about additions to the README file.

### CODE REVIEW

**Comment by gkatsev** [comment]
Hi @nweber, thanks for the PR. We're trying to come up with a better way of passing options to source handlers. See https://github.com/videojs/video.js/issues/2616
We probably won't pull this in until we resolve that (which, I think we're finally close to a consensus on what to do for it.

**Comment by forbesjo** [comment]
@gkatsev this change looks to be against the `1.x-dash.js-2.0.0` branch which is open against `1.x`. `1.x` is compatible with video.js 4.0 so it won't have access to any source handler enhancements.

**Comment by gkatsev** [comment]
Ah, missed that.

**Comment by gkatsev** [comment]
Is it still a tech then?

**Comment by gkatsev** [comment]
I guess it was still a source handler, I guess I forgot how early we got source handlers in videojs.

**Comment by gkatsev** [comment]
Also, the decisions we make for videojs/video.js#2616 may still be applicable to the older dash plugin.

**Comment by nweber** [comment]
Makes sense.  I'm going to close this one for now.  I've submitted a different pull request to enable a particular feature.

**Pull request closed without merging**
