### PR TITLE
Update gh-pages to 2.0.0

### PR DESCRIPTION
**Pull request by sprice**
Now that v2.0.0 is out we should update the demo site.

This PR is pretty messy as there are new versions of packages in node_modules.

The changes for package.json are:

-    "video.js": "^4.12.11",
-    "videojs-contrib-dash": "^1.0.0"
+    "video.js": "^5.0.2",
+    "videojs-contrib-dash": "^2.0.0"

I removed `videojs-automation` from this branch.

This branch also had `tmp/videojs-dash.min.js` even though this is not used in the source. I've removed it.

This commit also removes an npm-debug.log file.

### CODE REVIEW

**Comment by forbesjo** [comment]
Could you remove all the node_modules folder that are not necessary for the gh-pages page to work. Thanks!

**Comment by sprice** [comment]
As far as I can tell, the way the branch is organized at the moment, `node_modules` is required. It's in the current branch and `index.html` loads up quite a few assets from it.

If we are to remove it, how would you like the branch organized. Grunt scripts and `browserify`?

**Comment by gkatsev** [comment]
You can add just the specific files that are required in `node_modules` as opposed to all of `node_modules`.
For example: we only need `node_modules/bootstrap/dist/js/bootstrap.min.js` and `node_modules/bootstrap/dist/css/bootstrap.min.css` from bootstrap, everything else is unused.

**Comment by sprice** [comment]
Latest change removes `node_modules`, adds a `.gitignore`, and `Gruntfile.js`, and checks in files to `/js` and `/css`.

**Comment by sprice** [comment]
Hmm.... I tried squashing with previous commit to keep the commit history clean on a merge in. Not sure if that helps or hurts.

**Comment by sprice** [comment]
@forbesjo the `node_modules` folder is gone.

**Comment by forbesjo** [comment]
Awesome, thank you!

**Pull request merged**
