### PR TITLE
1.x dash.js 2.0.0 abr whitelisting

### PR DESCRIPTION
**Pull request by nweber**

### CODE REVIEW

**Comment by nweber** [comment]
+@dmlap

**Comment by forbesjo** [comment]
I will be merging in #48, this PR will have to be opened against the `1.x` branch and rebased.

**Comment by mrocajr** [comment]
@nweber Could you add a few unit tests for the whitelist functionality?  
Thanks.

**Comment by nweber** [comment]
Yeah, we're working on the unit tests.  Expect something in the morning.

**Comment by nweber** [comment]
Moving to a 1.x pull request.

**Pull request closed without merging**
